### PR TITLE
feat: Updated readme.md and uploaded the work done so far

### PR DESCRIPTION
**Pull request by DimpleB0501**

### CODE REVIEW

**Comment by debdutgoswami** [comment]
This PR can't be merged. Kindly create a PR to your **team** branch and not **master** branch.

**Comment by DimpleB0501** [comment]
Hi I checked now it doesnt have conflict with the main branch, can you try
merging the pull request

[image: image.png]

Regards
Dimple

**Comment by debdutgoswami** [comment]
Kindly go through the Readme in the master branch. You are not supposed to merge anything to master branch. Your team project will be inside the team branch.

**Comment by DimpleB0501** [comment]
I did exactly that. Is there a problem with the new pull request as well
I have used git push origin team(branch name) is that wrong??

**Comment by debdutgoswami** [comment]
Yes, my bad. I didn't check the new PR. I have merged it.

**Pull request closed without merging**
